config/routes.rb
Rails.application.routes.draw do

  resources :passwords do
    collection do
      post :verify
    end
  end

  devise_scope :user do
    get 'invitation' => 'invitation#invitation', as: 'invitation'
    post 'invitation' => 'invitation#register_invitation'
  end

  devise_for :users

  resources :groups do
    resources :users, only: [:index, :destroy]
    resources :invitations
  end

  root 'passwords#index'

end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :invitations, dependent: :destroy
  has_many :groups_users
  has_many :users, through: :groups_users
  has_many :admins, ->{ where("groups_users.admin = 1") }, through: :groups_users, source: :user
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  # GET /groups
  # GET /groups.json
  def index
    @groups = current_user.groups.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = current_user.groups.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        GroupsUser.create!(user_id: current_user.id, group_id: @group.id, admin: true)
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params[:group].permit(:name)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= simple_form_for(@group) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/groups/_subnav.html.erb
<ul class="nav nav-tabs nav-stacked">
  <li><%= link_to 'Passwords', @group, class: '' %></li>
  <li><%= link_to 'Members', group_users_path(@group), class: '' %></li>
</ul>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<h1>Groups</h1>
<table class="table">
  <thead>
    <tr>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.name %></td>
        <td>
          <%= link_to 'Show', group, class: 'btn-sm btn-primary'%>
          <%= link_to 'Edit', edit_group_path(group), class: 'btn-sm btn-warning' %>
          <%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn-sm btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'New Group', new_group_path %>

app/views/groups/new.html.erb
<h1>New group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-md-3">
    <%= render "subnav" %>
  </div>
  <div class="col-md-9">

  </div>
</div>
<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>