config/routes.rb
Rails.application.routes.draw do

  resources :passwords do
    collection do
      post :verify
    end
  end

  devise_scope :user do
    get 'invitation' => 'invitation#invitation', as: 'invitation'
    post 'invitation' => 'invitation#register_invitation'
  end

  devise_for :users

  resources :groups do
    resources :users, only: [:index, :destroy]
    resources :invitations
  end

  root 'passwords#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :lockable
  has_many :groups_users
  has_many :groups, through: :groups_users
  has_many :owned_groups, ->{ where("groups_users.admin = 1") }, through: :groups_users, source: :group
  has_many :passwords
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource :group
  load_and_authorize_resource :user, through: :group
  before_action :set_group

  def index
    @users = @group.users.all
    @invitation = Invitation.new
  end

  def destroy
    @group.users.delete(@group.users.find(params[:id]))
    redirect_to group_users_path(@group)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = current_user.groups.find(params[:group_id])
    end
end

app/views/users/index.html.erb
<div class="container">
  <h1>Members of <%= @group.name %></h1>
  <div class="row">
    <div class="col-md-3">
      <%= render 'groups/subnav' %>
    </div>
    <div class="col-md-9">
      <table class="table table-condensed table-bordered">
        <thead>
          <tr>
            <th>Name</th>
            <th>Email</th>
          </tr>
        </thead>

        <tbody>
          <% @group.users.each do |user| %>
            <tr>
              <td><%= user.email %></td>
              <td>
                <%= link_to 'Remove', group_user_path(@group, user), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-small' %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <fieldset>
        <legend>Invite someone</legend>
        <%= render 'invitations/form' %>
      </fieldset>

      <table class="table table-condensed table-bordered append">
        <thead>
          <tr>
            <th>Email</th>
            <th>Sent at</th>
          </tr>
        </thead>

        <tbody>
          <% @group.invitations(persisted: true).each do |invitation| %>
            <tr>
              <td><%= invitation.email %></td>
              <td><%= invitation.created_at %></td>
              <td>
                <%= link_to 'Revoke', group_invitation_path(@group, invitation), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-small' %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <br>

    </div>
  </div>
</div>